# Generated by Django 4.1.1 on 2022-11-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='CRN_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='write a description'),
        ),
        migrations.AddField(
            model_name='course',
            name='diffcality_type',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='easy', max_length=15),
        ),
        migrations.AddField(
            model_name='course',
            name='facality_members',
            field=models.TextField(default='write a facality member'),
        ),
        migrations.AddField(
            model_name='course',
            name='requirment',
            field=models.TextField(default='write a course requirment'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester_type',
            field=models.CharField(choices=[('Semester 5', 'Semester 5'), ('Semester 6', 'Semester 6'), ('Semester 7', 'Semester 7'), ('Semester 8', 'Semester 8'), ('Semester 9', 'Semester 9'), ('Semester 10', 'Semester 10')], default='Semester 5', max_length=15),
        ),
    ]
