# Generated by Django 4.1.1 on 2022-11-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_crn_num_course_credit_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
