# Generated by Django 4.1.1 on 2022-11-12 21:36

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to=course.models.image_upload),
        ),
    ]
