# Generated by Django 4.1.1 on 2023-02-15 22:34

import contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(default=1, upload_to=contact.models.image_upload),
            preserve_default=False,
        ),
    ]
