# Generated by Django 4.1.1 on 2023-02-12 21:43

from django.db import migrations, models
import learn.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='write a description')),
                ('urlLearn', models.URLField()),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('SW subjects', 'SW subjects'), ('Optional subjects', 'Optional subjects'), ('Others', 'Others')], default='SW subjects', max_length=100)),
                ('diffcality_type', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='easy', max_length=15)),
                ('semester_type', models.CharField(choices=[('Semester 5', 'Semester 5'), ('Semester 6', 'Semester 6'), ('Semester 7', 'Semester 7'), ('Semester 8', 'Semester 8'), ('Semester 9', 'Semester 9'), ('Semester 10', 'Semester 10')], default='Semester 5', max_length=15)),
                ('image', models.ImageField(upload_to=learn.models.image_upload)),
                ('video', models.ImageField(upload_to=learn.models.Video_upload)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
