# Generated by Django 4.1.1 on 2023-02-12 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='course',
            new_name='learn',
        ),
    ]
