# Generated by Django 4.1.1 on 2023-02-12 22:01

from django.db import migrations, models
import learn.models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_rename_course_learn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn',
            name='video',
            field=models.FileField(upload_to=learn.models.Video_upload),
        ),
    ]
