# Generated by Django 4.1.1 on 2023-02-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_alter_learn_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learn',
            name='video',
        ),
        migrations.AddField(
            model_name='learn',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
